name: Build APK Real Runner

on:
  workflow_dispatch:
    inputs:
      source_type:
        description: 'Source type'
        required: true
        default: 'git_url'
      source_url:
        description: 'Target Source URL'
        required: true
        default: 'https://github.com/flutter/samples'
      build_type:
        description: 'Build variant'
        required: true
        default: 'release'
      chat_id:
        description: 'Telegram Chat ID'
        required: true
      status_message_id:
        description: 'Status Message ID'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Telegram
        run: |
          curl -s -X POST 'https://api.telegram.org/bot7824380847:AAGJ6ahNX4PtyDEw9LHSEgUF0KErzgcvyh0/sendMessage'             -d 'chat_id=7829018304'             -d 'text=🚀 REAL GITHUB RUNNER IS RUNNING ON UBUNTU VM!'
